// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebUI.Infrastructure;

#nullable disable

namespace WebUI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428113522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("WebUI.Domain.Entities.DivisionFrequencyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_from");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("active_to");

                    b.Property<Guid>("DivisionProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("division_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("DivisionProfileId")
                        .HasDatabaseName("ix_division_frequency_assignments_division_profile_id");

                    b.ToTable("division_frequency_assignments", (string)null);
                });

            modelBuilder.Entity("WebUI.Domain.Entities.DivisionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("division_profiles", (string)null);
                });

            modelBuilder.Entity("WebUI.Domain.Entities.InterceptionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("CanBePutOnMap")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_be_put_on_map");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_text");

                    b.Property<DateTime>("ObservedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_date");

                    b.Property<Guid>("RegistryInterceptionActionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("registry_interception_action_id");

                    b.Property<int>("UnknownParticipantCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unknown_participant_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ObservedDate")
                        .HasDatabaseName("ix_interception_messages_observed_date");

                    b.HasIndex("RegistryInterceptionActionId")
                        .HasDatabaseName("ix_interception_messages_registry_interception_action_id");

                    b.ToTable("interception_messages", (string)null);
                });

            modelBuilder.Entity("WebUI.Domain.Entities.MilitaryProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("callsign");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DivisionProfileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("division_profile_id");

                    b.Property<Guid?>("RegistryInterceptionParticipantRoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("registry_interception_participant_role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DivisionProfileId")
                        .HasDatabaseName("ix_military_profiles_division_profile_id");

                    b.HasIndex("RegistryInterceptionParticipantRoleId")
                        .HasDatabaseName("ix_military_profiles_registry_interception_participant_role_id");

                    b.ToTable("military_profiles", (string)null);
                });

            modelBuilder.Entity("WebUI.Domain.Entities.RegistryInterceptionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("registry_interception_actions", (string)null);
                });

            modelBuilder.Entity("WebUI.Domain.Entities.RegistryInterceptionParticipantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("registry_interception_participant_roles", (string)null);
                });

            modelBuilder.Entity("WebUI.Domain.Entities.DivisionFrequencyAssignment", b =>
                {
                    b.HasOne("WebUI.Domain.Entities.DivisionProfile", null)
                        .WithMany()
                        .HasForeignKey("DivisionProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("WebUI.Domain.ValueObjects.FrequencyCodeVo", "FrequencyCode", b1 =>
                        {
                            b1.Property<Guid>("DivisionFrequencyAssignmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("frequency_code");

                            b1.HasKey("DivisionFrequencyAssignmentId");

                            b1.ToTable("division_frequency_assignments");

                            b1.WithOwner()
                                .HasForeignKey("DivisionFrequencyAssignmentId");
                        });

                    b.Navigation("FrequencyCode")
                        .IsRequired();
                });

            modelBuilder.Entity("WebUI.Domain.Entities.DivisionProfile", b =>
                {
                    b.OwnsOne("WebUI.Domain.ValueObjects.DivisionNameVo", "Name", b1 =>
                        {
                            b1.Property<Guid>("DivisionProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("DivisionProfileId");

                            b1.ToTable("division_profiles");

                            b1.WithOwner()
                                .HasForeignKey("DivisionProfileId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("WebUI.Domain.Entities.InterceptionMessage", b =>
                {
                    b.HasOne("WebUI.Domain.Entities.RegistryInterceptionAction", null)
                        .WithMany()
                        .HasForeignKey("RegistryInterceptionActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("WebUI.Domain.Entities.InterceptionCommandVector", "CommandVectors", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<Guid>("FromParticipantId")
                                .HasColumnType("TEXT")
                                .HasColumnName("from_participant_id");

                            b1.Property<Guid>("InterceptionMessageId")
                                .HasColumnType("TEXT")
                                .HasColumnName("interception_message_id");

                            b1.Property<Guid>("ToParticipantId")
                                .HasColumnType("TEXT")
                                .HasColumnName("to_participant_id");

                            b1.HasKey("Id");

                            b1.HasIndex("InterceptionMessageId")
                                .HasDatabaseName("ix_interception_command_vectors_interception_message_id");

                            b1.HasIndex("FromParticipantId", "ToParticipantId")
                                .HasDatabaseName("ix_interception_command_vectors_from_to_participants");

                            b1.ToTable("interception_command_vectors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InterceptionMessageId");
                        });

                    b.OwnsOne("WebUI.Domain.ValueObjects.DivisionNameVo", "DivisionName", b1 =>
                        {
                            b1.Property<Guid>("InterceptionMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("division_name");

                            b1.HasKey("InterceptionMessageId");

                            b1.ToTable("interception_messages");

                            b1.WithOwner()
                                .HasForeignKey("InterceptionMessageId");
                        });

                    b.OwnsOne("WebUI.Domain.ValueObjects.FrequencyCodeVo", "FrequencyCode", b1 =>
                        {
                            b1.Property<Guid>("InterceptionMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("frequency_code");

                            b1.HasKey("InterceptionMessageId");

                            b1.ToTable("interception_messages");

                            b1.WithOwner()
                                .HasForeignKey("InterceptionMessageId");
                        });

                    b.OwnsMany("WebUI.Domain.Entities.InterceptionParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("Callsign")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("callsign");

                            b1.Property<Guid>("InterceptionMessageId")
                                .HasColumnType("TEXT")
                                .HasColumnName("interception_message_id");

                            b1.Property<Guid>("MilitaryProfileId")
                                .HasColumnType("TEXT")
                                .HasColumnName("military_profile_id");

                            b1.Property<Guid?>("RegistryInterceptionParticipantRoleId")
                                .HasColumnType("TEXT")
                                .HasColumnName("registry_interception_participant_role_id");

                            b1.HasKey("Id");

                            b1.HasIndex("InterceptionMessageId")
                                .HasDatabaseName("ix_interception_participants_interception_message_id");

                            b1.HasIndex("MilitaryProfileId")
                                .HasDatabaseName("ix_interception_participants_military_profile_id");

                            b1.HasIndex("RegistryInterceptionParticipantRoleId")
                                .HasDatabaseName("ix_interception_participants_registry_interception_participant_role_id");

                            b1.ToTable("interception_participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InterceptionMessageId");

                            b1.HasOne("WebUI.Domain.Entities.MilitaryProfile", null)
                                .WithMany()
                                .HasForeignKey("MilitaryProfileId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("WebUI.Domain.Entities.RegistryInterceptionParticipantRole", null)
                                .WithMany()
                                .HasForeignKey("RegistryInterceptionParticipantRoleId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.OwnsOne("WebUI.Domain.ValueObjects.DivisionNameVo", "DivisionName", b2 =>
                                {
                                    b2.Property<Guid>("InterceptionParticipantId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("division_name");

                                    b2.HasKey("InterceptionParticipantId");

                                    b2.ToTable("interception_participants");

                                    b2.WithOwner()
                                        .HasForeignKey("InterceptionParticipantId");
                                });

                            b1.Navigation("DivisionName");
                        });

                    b.Navigation("CommandVectors");

                    b.Navigation("DivisionName");

                    b.Navigation("FrequencyCode")
                        .IsRequired();

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("WebUI.Domain.Entities.MilitaryProfile", b =>
                {
                    b.HasOne("WebUI.Domain.Entities.DivisionProfile", null)
                        .WithMany()
                        .HasForeignKey("DivisionProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebUI.Domain.Entities.RegistryInterceptionParticipantRole", null)
                        .WithMany()
                        .HasForeignKey("RegistryInterceptionParticipantRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("WebUI.Domain.Entities.MilitaryProfileFrequency", "Frequencies", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("MilitaryProfileId")
                                .HasColumnType("TEXT")
                                .HasColumnName("military_profile_id");

                            b1.HasKey("Id");

                            b1.HasIndex("MilitaryProfileId")
                                .HasDatabaseName("ix_military_profile_frequencies_military_profile_id");

                            b1.ToTable("military_profile_frequencies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MilitaryProfileId");

                            b1.OwnsOne("WebUI.Domain.ValueObjects.FrequencyCodeVo", "FrequencyCode", b2 =>
                                {
                                    b2.Property<Guid>("MilitaryProfileFrequencyId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("frequency_code");

                                    b2.HasKey("MilitaryProfileFrequencyId");

                                    b2.ToTable("military_profile_frequencies");

                                    b2.WithOwner()
                                        .HasForeignKey("MilitaryProfileFrequencyId");
                                });

                            b1.Navigation("FrequencyCode")
                                .IsRequired();
                        });

                    b.Navigation("Frequencies");
                });

            modelBuilder.Entity("WebUI.Domain.Entities.RegistryInterceptionAction", b =>
                {
                    b.OwnsOne("WebUI.Domain.ValueObjects.InterceptionActionNameVo", "Name", b1 =>
                        {
                            b1.Property<Guid>("RegistryInterceptionActionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("RegistryInterceptionActionId");

                            b1.ToTable("registry_interception_actions");

                            b1.WithOwner()
                                .HasForeignKey("RegistryInterceptionActionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("WebUI.Domain.Entities.RegistryInterceptionParticipantRole", b =>
                {
                    b.OwnsOne("WebUI.Domain.ValueObjects.ParticipantRoleNameVo", "Name", b1 =>
                        {
                            b1.Property<Guid>("RegistryInterceptionParticipantRoleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("RegistryInterceptionParticipantRoleId");

                            b1.ToTable("registry_interception_participant_roles");

                            b1.WithOwner()
                                .HasForeignKey("RegistryInterceptionParticipantRoleId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
